detect_arrow:
  ros__parameters:
    ArrowDetectorPixelNumMax:
      type: int
      value: 80000
    ArrowDetectorPixelNumMin:
      type: int
      value: 15000
    ArrowDetectorLengthWidthRatioMax:
      type: double
      value: 2.8284271247461900976033774484194
    ArrowDetectorLengthWidthRatioMin:
      type: double
      value: 1.1
    ArrowDetectorApproxSizeMax:
      type: int
      value: 10
    ArrowDetectorApproxSizeMin:
      type: int
      value: 6
    ArrowDetectorCannyThreshold1:
      type: int
      value: 100
    ArrowDetectorCannyThreshold2:
      type: int
      value: 200
    ArrowDetectorHoughRho:
      type: double
      value: 0.25
    ArrowDetectorHoughTheta:
      type: double
      value: 0.00436332312986111111111111111111
    ArrowDetectorHoughThreshold:
      type: int
      value: 35
    ArrowDetectParallelThreshold:
      type: double
      value: 0.52359877558333333333333333333333
    ArrowDetectorThresholdThresh:
      type: int
      value: 120
    ArrowDetectorThresholdMaxval:
      type: int
      value: 300