RedeemBox_detector:
  ros__parameters:
    CloudPointTopic: "sensor/RealSense/point_cloud"
    ImageTopic: "/sensor/camera/images"
    CloudPointFrame: "sensor/RealSense/depth"
    ImageFrame: "sensor/camera"