---

camera:
  height: 1080
  width: 1920
  dist_coeffs: [-0.1131506181237709, 0.1301328009901622, -0.0007416862926336681, 0.0003741668262735999, 0.06347345493061382]
  camera_matrix: [2413.820435449382, 0, 658.3681795085505 , 0, 2418.356696660543, 568.1925341729512, 0.0, 0.0, 1.0]
  ExposureTimeLower: 15000
  ExposureTimeUpper: 15000
  Gain: 7.0

redeem_box:
# 兑换框的四个角点，单位是m，坐标是以侧面箭头顶点位原点，z轴指向内侧的右手系
  redeemptionBoxCornerPoints:
    - [-0.12, 0.12, 0]
    - [0.12, 0.12, 0]
    - [0.12, -0.12, 0]
    - [-0.12, -0.12, 0]
    # 箭头指向的那边的那条直线的起点和终点，单位是m，坐标是以侧面箭头顶点位原点，z轴指向内侧的右手系
  line:
    - [0.144, 0.144, 0.]
    - [0.144, -0.144, 0.]
  # frontface center
  center: [0.0, 0.0, 0.0]

arrow:
  # 箭头的8个角点，单位是m，坐标是以侧面箭头顶点位原点，z轴指向内侧的右手系
  # 顺序是：
  # 1. 外侧顶点
  # 2. 内侧顶点
  # 3. x轴外侧
  # 4. x轴内侧
  # 5. y轴外侧
  # 6. y轴内侧
  # 7. 内侧y轴与外侧x轴的交点
  # 8. 内侧x轴与外侧y轴的交点
  arrowPoints:
  - [0.144, 0, 0.0455]
  - [0.144, 0, 0.059642135623730955]
  - [0.144, -0.1, 0.1455]
  - [0.144, -0.08585786437626905, 0.1455]
  - [0.144, 0.1, 0.1455]
  - [0.144, 0.08585786437626905, 0.1455]
  - [0.144, -0.007071067811865476, 0.05257106781186548]
  - [0.144, 0.007071067811865476, 0.05257106781186548]

# 存一些箭头检测的参数
arrow_detect:
  ArrowDetectorPixelNumMax: 80000
  ArrowDetectorPixelNumMin: 5000
  ArrowDetectorLengthWidthRatioMax: 3
  ArrowDetectorLengthWidthRatioMin: 1.1
  ArrowDetectorApproxSizeMax: 8.
  ArrowDetectorApproxSizeMin: 6.
  ArrowDetectorCannyThreshold1: 100.
  ArrowDetectorCannyThreshold2: 200.
  ArrowDetectorHoughRho: 0.25
  ArrowDetectorHoughTheta: 0.00436332312998582394230922638889
  ArrowDetectorHoughThreshold: 35.
  ArrowDetectParallelThreshold: 0.523598775598298873077
  ArrowDetectorThresholdThresh: 100.
  ArrowDetectorThresholdMaxval: 300.
  ArrowDetectorThresholdThreshold: 5.
  ArrowDetectorIterations: 5.
  ArrowDetectorapproxPolyDPEpsilon: 10.
  ArrowDetectorLongShortRateMax: 20.
  ArrowDetectorLongShortRateMin: 5.
  PCLManager:
    ransacDistanceThreshold: 1
    ransacMaxIterations: 1000

mid_360:
  buffertime: 200 # ms int

object_pos:
  arm: # arm to map
    translation:
      x: 0.
      y: 0.
      z: 0.
    rotate:
      w: 0.7071068
      x: 0.
      y: 0.
      z: 0.7071068
  camera: # camera to map
    translation:
      x: 0.
      y: 0.
      z: 0.01443
    rotate:
      w: 0.7071068
      x: -0.7071068
      y: 0.
      z: 0.
  mid360: # mid360 to map
    translation:
      x: 0.06623
      y: -0.03333
      z: 0.047
    rotate:
      w: 0.
      x: 0.
      y: 0.
      z: 1.
  

